#pragma pattern_limit 100000000

//#define __DATA_ARENA 1
//#define __DATA_AUTOMATIC_SKILLS 1
//#define __DATA_CRAFTING 1
//#define __DATA_DATA_COUNTERS 1
//#define __DATA_DECOID 1
//#define __DATA_EQUIPMENTS 1
//#define __DATA_EXTRA_COUNTERS 1
//#define __DATA_ITEMS 1
//#define __DATA_MISSIONS 1
//#define __DATA_MONSTERS 1
//#define __DATA_PART_BREAKS 1
//#define __DATA_QUESTS 1
//#define __DATA_SEASONAL_EVENTS 1
//#define __DATA_SHARPNESS 1
//#define __DATA_SHOP_ROAD_CAT 1
//#define __DATA_SHOP_TOWER_MEDAL 1
//#define __DATA_SHOP 1
//#define __DATA_WEAPONS 1

#include <mhfdat/index.hexpat>